services:
  subtitle-translator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: subtitle-translator
    user: ${PUID}:${PGID}
    group_add:
      - 105
    environment:
      - TZ=${TZ}
      - HF_TOKEN=${HF_TOKEN}
      - TARGET_LANG=${TARGET_LANG:-Spanish}
    volumes:
      - ${MEDIA_PATH}/Series:/videos
      - ./database:/app/database
    command:
      - ./subtitle-translator
      - -dir
      - /videos
      - -target
      - ${TARGET_LANG:-Spanish}
      - -verbose
    ports:
      - "9595:9595"
    restart: unless-stopped
    network_mode: host
    privileged: true
